/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

import javax.swing.ImageIcon;
import utility.Operation;

/**
 *
 * @author LENOVO
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        setSize(1000,1000);
        ImageIcon ic = new ImageIcon("E:\\ClientProject\\Accounts\\src\\screens\\logo.png");
        setIconImage(ic.getImage());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deskpane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuLedger = new javax.swing.JMenu();
        jmiAddNewLedger = new javax.swing.JMenuItem();
        jmiLedgerEntry = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        deskpane.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                deskpaneKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                deskpaneKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout deskpaneLayout = new javax.swing.GroupLayout(deskpane);
        deskpane.setLayout(deskpaneLayout);
        deskpaneLayout.setHorizontalGroup(
            deskpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
        );
        deskpaneLayout.setVerticalGroup(
            deskpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        getContentPane().add(deskpane, java.awt.BorderLayout.CENTER);

        menuLedger.setText("Ledger");

        jmiAddNewLedger.setText("Start New Ledger");
        jmiAddNewLedger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddNewLedgerActionPerformed(evt);
            }
        });
        menuLedger.add(jmiAddNewLedger);

        jmiLedgerEntry.setText("Ledger Entry");
        jmiLedgerEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLedgerEntryActionPerformed(evt);
            }
        });
        menuLedger.add(jmiLedgerEntry);

        jMenuBar1.add(menuLedger);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAddNewLedgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddNewLedgerActionPerformed
        Operation.openInternalFrame(deskpane, new StartNewLedger());
    }//GEN-LAST:event_jmiAddNewLedgerActionPerformed

    private void jmiLedgerEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLedgerEntryActionPerformed
        Operation.openInternalFrame(deskpane, new LedgerEntryForm(deskpane));
    }//GEN-LAST:event_jmiLedgerEntryActionPerformed

    private void deskpaneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deskpaneKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_deskpaneKeyTyped

    private void deskpaneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deskpaneKeyPressed
        
    }//GEN-LAST:event_deskpaneKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane deskpane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiAddNewLedger;
    private javax.swing.JMenuItem jmiLedgerEntry;
    private javax.swing.JMenu menuLedger;
    // End of variables declaration//GEN-END:variables

}
