/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import model.dao.AccountInfoDAO;
import model.to.AccountInfoTO;
import utility.Validations;

/**
 *
 * @author LENOVO
 */
public class StartNewLedger extends javax.swing.JInternalFrame {

    /**
     * Creates new form StartNewLedger
     */
    public StartNewLedger() {
        initComponents();
        InputMap im = this.getInputMap(WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        ActionMap am = this.getActionMap();

        im.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "spaced");
        am.put("spaced", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnStart.doClick();
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfAccountName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        jtfOpenBalance = new controls.FloatTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Start New Ledger");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Enter Account Name : ");

        jtfAccountName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtfAccountName.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Enter Open Balance : ");

        btnStart.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnStart.setText("Start Ledger");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        jtfOpenBalance.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfAccountName)
                            .addComponent(jtfOpenBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfOpenBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        String message = "";
        boolean allvalid = true;
        String accountname = jtfAccountName.getText().trim();
        String openingbalance = jtfOpenBalance.getText().trim();
        if (Validations.isEmpty(accountname)) {
            message += "Please Enter Some Value in Account Name\n\n";
            allvalid = false;
        }
        if (Validations.isEmpty(openingbalance)) {
            message += "Please Enter Some Value in Opening Balance\n\n";
            allvalid = false;
        } else if (!Validations.isFloat(openingbalance)) {
            message += "Please Enter Number in Opening Balance\n\n";
            allvalid = false;
        }
        if (allvalid) {
            AccountInfoTO ait = new AccountInfoTO();
            ait.setAccountname(accountname);
            ait.setOpeningbalance(Float.parseFloat(openingbalance));
            ait.setCurrentbalance(Float.parseFloat(openingbalance));
            AccountInfoDAO dao = new AccountInfoDAO();
            if (dao.insertRecord(ait)) {
                message = "New Ledger is Started";
                //Operation.openInternalFrame(getDesktopPane(), new LedgerEntryForm(ait));
                dispose();
            } else {
                message = dao.getErrorMessage();
                if (message.contains("UNIQUE")) {
                    message = "Account Name is Already Entered";
                }
            }
        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnStartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jtfAccountName;
    private controls.FloatTextField jtfOpenBalance;
    // End of variables declaration//GEN-END:variables
}
